language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - TYPO3_VERSION=^10.4 COVERAGE=0

matrix:
  include:
  - env: TYPO3_VERSION=^10.4 COVERAGE=1
    php: 7.2
  exclude:
  - env: TYPO3_VERSION=^10.4 COVERAGE=0
    php: 7.2

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - mkdir -p build/logs

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --configuration phpunit.xml.dist --colors Tests/Unit/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests with coverage";
      .Build/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-text --coverage-clover build/logs/clover.xml Tests/Unit/
    fi

after_script:
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      travis_retry php .Build/bin/coveralls -v
    fi
